import personal_data

print("--- PERSONAL INFORMATION ---")
print(f"Name: {personal_data.full_name}")
print(f"Age: {personal_data.age}")
print(f"Height: {personal_data.height}")
print(f"Weight: {personal_data.weight}")
print()
print(f"Phone Number: {personal_data.phone_number}")
print(f"Email: {personal_data.email}")
print()
print("--- STRING OPERATIONS ---")
print(f"Name Upper: {personal_data.name_upper}")
print(f"Name Lower: {personal_data.name_lower}")
print(f"Name Length: {personal_data.name_length}")
print(f"City Name Upper: {personal_data.cityname_upper}")
print()
print("--- ADDRESS ---")
print(f"Full Address: {personal_data.full_address}")
print(f"Full Address Length: {personal_data.full_address_length}")