import school_data

print("><><><<><><> SCHOOL DATA ><><><<><><>")
print()
print("--- Student's information ---")
print(f"Student name: {school_data.student_name}")
print(f"Student ID: {school_data.student_ID}")
print(f"Age: {school_data.age}")
print()
print("--- Course's information ---")
print(f"Course code: {school_data.course_code}")
print(f"Course name: {school_data.course_name}")
print()
print("--- Total Score ---")
print(f"Random Score 1: {school_data.score1}")
print(f"Random Score 2: {school_data.score2}")
print()
print("---Student's Name String Operations---")
print(f"Upper: {school_data.name_upper}")
print(f"Lower: {school_data.name_lower}")
print(f"Length: {school_data.name_length}")